# XEOX Gamepad SL-6556-BK:
# Forward/Rotate controlled by left stick.

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.1
    scale_linear_turbo:
      x: 0.2

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 0.6

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button

joy_node:
  ros__parameters:
    deadzone: .05
